"""M11 ontology-bounded physical-planning contracts and algorithms."""

from xgap.planning.contracts import (
    ConfidenceContext,
    CostPrediction,
    ExchangeDecision,
    ExchangeStrategy,
    ExecutionObservation,
    FeatureVector,
    LogicalDependency,
    LogicalOperatorSpec,
    MappingSufficiencyResult,
    MappingSufficiencyStatus,
    ObjectiveScore,
    OntologyAlignmentContext,
    PhysicalCompilationResult,
    PhysicalPlan,
    PhysicalRealization,
    PhysicalState,
    PlacementDecision,
    PlanningConfig,
    PlanningTraceEvent,
    QueryPlanningContext,
    SemanticDeviationResult,
    SemanticDeviationStatus,
    objective_score,
)
from xgap.planning.ontology import (
    AlignmentArtifactError,
    ArtifactOntologyAlignmentProvider,
    ProvidedSemanticDeviationScorer,
)
from xgap.planning.cost import (
    OBSERVATION_STORE_VERSION,
    ExecutionObservationStore,
    GaussianProcessConfig,
    GaussianProcessCostEstimator,
    StateSpaceBound,
    across_task_confidence_context,
    across_task_delta,
    confidence_beta,
    conservative_state_space_bound,
    gaussian_process_negative_log_marginal_likelihood,
    make_execution_observation,
)
from xgap.planning.budget import FixedBudgetPolicy, PolynomialBudgetPolicy
from xgap.planning.compiler import ExistingCompilerAdapter
from xgap.planning.features import DeterministicStateFeatureExtractor
from xgap.planning.search import (
    BnBSearchResult,
    ExchangeCatalog,
    SearchRunContext,
    bnb_search,
    enumerate_successors,
)
from xgap.planning.planner import (
    CandidatePlanningRecord,
    MainPlannerResult,
    SelectedPhysicalPlan,
    XGAPPhysicalPlanner,
)
from xgap.planning.oracle import (
    ExhaustiveOracleResult,
    ExhaustivePlanRecord,
    OracleComparison,
    budget_quality_curve,
    compare_search_with_oracle,
    exhaustive_physical_oracle,
)
from xgap.planning.topology import IndexedLogicalPlan, index_logical_plan
from xgap.planning.trace import read_search_trace, write_search_trace

__all__ = [
    "AlignmentArtifactError",
    "ArtifactOntologyAlignmentProvider",
    "BnBSearchResult",
    "ConfidenceContext",
    "CostPrediction",
    "CandidatePlanningRecord",
    "DeterministicStateFeatureExtractor",
    "ExchangeDecision",
    "ExchangeCatalog",
    "ExchangeStrategy",
    "ExhaustiveOracleResult",
    "ExhaustivePlanRecord",
    "ExecutionObservation",
    "ExecutionObservationStore",
    "ExistingCompilerAdapter",
    "FeatureVector",
    "FixedBudgetPolicy",
    "GaussianProcessConfig",
    "GaussianProcessCostEstimator",
    "IndexedLogicalPlan",
    "LogicalDependency",
    "LogicalOperatorSpec",
    "MappingSufficiencyResult",
    "MappingSufficiencyStatus",
    "MainPlannerResult",
    "ObjectiveScore",
    "OracleComparison",
    "OBSERVATION_STORE_VERSION",
    "OntologyAlignmentContext",
    "PhysicalCompilationResult",
    "PhysicalPlan",
    "PhysicalRealization",
    "PhysicalState",
    "PlacementDecision",
    "PlanningConfig",
    "PlanningTraceEvent",
    "PolynomialBudgetPolicy",
    "ProvidedSemanticDeviationScorer",
    "QueryPlanningContext",
    "SemanticDeviationResult",
    "SemanticDeviationStatus",
    "SelectedPhysicalPlan",
    "SearchRunContext",
    "StateSpaceBound",
    "XGAPPhysicalPlanner",
    "across_task_confidence_context",
    "across_task_delta",
    "bnb_search",
    "budget_quality_curve",
    "confidence_beta",
    "conservative_state_space_bound",
    "compare_search_with_oracle",
    "enumerate_successors",
    "exhaustive_physical_oracle",
    "gaussian_process_negative_log_marginal_likelihood",
    "index_logical_plan",
    "make_execution_observation",
    "objective_score",
    "read_search_trace",
    "write_search_trace",
]
