"""Path-pattern query AST and lowering interfaces."""

from xgap.pattern.ast import (
    Alt,
    Bounded,
    Direction,
    EdgePattern,
    NodePattern,
    OptionalExpr,
    PathMode,
    PathPatternQuery,
    Plus,
    Rel,
    RegexExpr,
    Selector,
    SelectorKind,
    Seq,
    Star,
    Var,
)
from xgap.pattern.lowering import (
    LoweringError,
    apply_selector,
    lower_path_pattern,
    lower_regex,
    lower_to_logical_plan,
)
from xgap.pattern.quantified_ast import (
    CountingQuantifier,
    FocusedEdgePattern,
    FocusedNodePattern,
    FocusedQuantifiedPatternQuery,
    PropertyPredicate,
    QuantifiedPatternEdge,
    QuantifierComparator,
    QuantifierKind,
    ScalarComparator,
    all_matches,
    count_eq,
    count_ge,
    exists,
    none,
    ratio_eq,
    ratio_ge,
)
from xgap.pattern.quantified_lowering import (
    QuantifiedLoweringError,
    lower_focused_quantified_pattern,
)
from xgap.pattern.quantified_typecheck import (
    QuantifiedPatternTypeError,
    QuantifierBounds,
    type_check_focused_quantified_pattern,
    validate_quantifier_bounds,
)
from xgap.pattern.typecheck import PatternTypeError, infer_schema, type_check_path_pattern
from xgap.pattern.types import PatternVarType

__all__ = [
    "Alt",
    "Bounded",
    "CountingQuantifier",
    "Direction",
    "EdgePattern",
    "FocusedEdgePattern",
    "FocusedNodePattern",
    "FocusedQuantifiedPatternQuery",
    "LoweringError",
    "NodePattern",
    "OptionalExpr",
    "PathMode",
    "PathPatternQuery",
    "PatternTypeError",
    "PatternVarType",
    "Plus",
    "PropertyPredicate",
    "QuantifiedPatternEdge",
    "QuantifiedLoweringError",
    "QuantifiedPatternTypeError",
    "QuantifierBounds",
    "QuantifierComparator",
    "QuantifierKind",
    "RegexExpr",
    "Rel",
    "ScalarComparator",
    "Selector",
    "SelectorKind",
    "Seq",
    "Star",
    "Var",
    "all_matches",
    "apply_selector",
    "count_eq",
    "count_ge",
    "exists",
    "infer_schema",
    "lower_focused_quantified_pattern",
    "lower_path_pattern",
    "lower_regex",
    "lower_to_logical_plan",
    "none",
    "ratio_eq",
    "ratio_ge",
    "type_check_focused_quantified_pattern",
    "type_check_path_pattern",
    "validate_quantifier_bounds",
]
