"""Typed tools and pluggable graph-backend adapters."""

from xgap.tools.backends import (
    BACKEND_INVOKE_TOOL,
    BackendInvokeTool,
    BackendObservationCatalog,
    BackendOperation,
    BackendPlugin,
    BackendPluginRegistry,
    CatalogBackendPlugin,
    NativeBackendPlugin,
)
from xgap.tools.contracts import (
    AgentTool,
    FunctionTool,
    ToolContext,
    ToolEffect,
    ToolResult,
    ToolSpec,
    ToolStatus,
)
from xgap.tools.registry import ToolRegistry, ToolRegistryError
from xgap.tools.remote import (
    REMOTE_EXECUTOR_TOOL,
    RemoteCommandResult,
    RemoteExecutorOperation,
    RemoteExecutorPlugin,
    RemoteExecutorRegistry,
    RemoteExecutorTool,
    RemoteJobState,
    RemoteTransport,
    SlurmRemoteExecutor,
    SshTransport,
)
from xgap.tools.resolution import (
    SEMANTIC_CATALOG_LOOKUP_TOOL,
    SEMANTIC_LLM_PROPOSE_TOOL,
    SEMANTIC_ONTOLOGY_LOOKUP_TOOL,
    USER_CLARIFY_TOOL,
    ResolutionCandidateProvider,
    ResolutionCandidateRequest,
    ResolutionCandidateResponse,
    ResolutionCandidateTool,
)

__all__ = [
    "AgentTool",
    "BACKEND_INVOKE_TOOL",
    "BackendInvokeTool",
    "BackendObservationCatalog",
    "BackendOperation",
    "BackendPlugin",
    "BackendPluginRegistry",
    "CatalogBackendPlugin",
    "FunctionTool",
    "NativeBackendPlugin",
    "REMOTE_EXECUTOR_TOOL",
    "RemoteCommandResult",
    "RemoteExecutorOperation",
    "RemoteExecutorPlugin",
    "RemoteExecutorRegistry",
    "RemoteExecutorTool",
    "RemoteJobState",
    "RemoteTransport",
    "ResolutionCandidateProvider",
    "ResolutionCandidateRequest",
    "ResolutionCandidateResponse",
    "ResolutionCandidateTool",
    "SEMANTIC_CATALOG_LOOKUP_TOOL",
    "SEMANTIC_LLM_PROPOSE_TOOL",
    "SEMANTIC_ONTOLOGY_LOOKUP_TOOL",
    "SlurmRemoteExecutor",
    "SshTransport",
    "ToolContext",
    "ToolEffect",
    "ToolRegistry",
    "ToolRegistryError",
    "ToolResult",
    "ToolSpec",
    "ToolStatus",
    "USER_CLARIFY_TOOL",
]
