"""Path-algebra data structures and logical operators."""

from xgap.algebra.bindings import BindingField, BindingKind, BindingRelation, BindingRow, BindingSchema
from xgap.algebra.conditions import (
    And,
    EdgeRef,
    LabelEquals,
    LengthEquals,
    NodeNotEquals,
    NodeRef,
    Not,
    Or,
    PropertyEquals,
    PropertyGreaterThan,
    PropertyGreaterThanOrEqual,
    PropertyLessThan,
    PropertyLessThanOrEqual,
    PropertyNotEquals,
)
from xgap.algebra.evaluator import evaluate
from xgap.algebra.graph import PropertyGraph
from xgap.algebra.ops import (
    AntiSemiJoinOp,
    BindEdgeOp,
    BindNodeOp,
    BindingJoinOp,
    BindingProjectOp,
    EdgesOp,
    FocusProjectionOp,
    GroupByOp,
    JoinOp,
    NodesOp,
    OrderByOp,
    ProjectionOp,
    QuantifiedCheckOp,
    RecursiveMode,
    RecursiveOp,
    SelectionOp,
    UnionOp,
)
from xgap.algebra.types import Path, PathSet, SolutionSpace

__all__ = [
    "And",
    "AntiSemiJoinOp",
    "BindEdgeOp",
    "BindNodeOp",
    "BindingField",
    "BindingKind",
    "BindingJoinOp",
    "BindingProjectOp",
    "BindingRelation",
    "BindingRow",
    "BindingSchema",
    "EdgeRef",
    "EdgesOp",
    "FocusProjectionOp",
    "GroupByOp",
    "JoinOp",
    "LabelEquals",
    "LengthEquals",
    "NodeNotEquals",
    "NodeRef",
    "NodesOp",
    "Not",
    "Or",
    "OrderByOp",
    "Path",
    "PathSet",
    "ProjectionOp",
    "PropertyEquals",
    "PropertyGreaterThan",
    "PropertyGreaterThanOrEqual",
    "PropertyLessThan",
    "PropertyLessThanOrEqual",
    "PropertyNotEquals",
    "QuantifiedCheckOp",
    "PropertyGraph",
    "RecursiveMode",
    "RecursiveOp",
    "SelectionOp",
    "SolutionSpace",
    "UnionOp",
    "evaluate",
]
